#include "netpulse/transport.hpp"
#include "netpulse/stats.hpp" // now_secs
#include "netpulse/platform.hpp"

#include <cstring>
#include <cctype>
#include <chrono>
#include <map>
#include <memory>
#include <thread>

#ifdef _WIN32
#  ifndef NOMINMAX
#    define NOMINMAX
#  endif
#  include <winsock2.h>
#  include <ws2tcpip.h>
#  include <iphlpapi.h>
// BUG FIX: SIO_RCVALL lives in mstcpip.h specifically. MinGW's own
// ws2tcpip.h happens to pull that in transitively, so the cross-compile
// verification used to develop this passed clean and completely missed
// that the real Microsoft Windows SDK (MSVC) does NOT do the same — a real
// build failed with 'SIO_RCVALL': undeclared identifier. Explicit is
// correct on every toolchain regardless of what any of them happen to
// pull in as a side effect of something else.
#  include <mstcpip.h>
#  include <timeapi.h>
#  pragma comment(lib, "Ws2_32.lib")
#  pragma comment(lib, "Iphlpapi.lib")
#  pragma comment(lib, "Winmm.lib")
using socklen_t = int;
#  define CLOSESOCK closesocket
#  define LASTERR WSAGetLastError()
#  define WOULDBLOCK WSAEWOULDBLOCK
#else
#  include <arpa/inet.h>
#  include <netinet/in.h>
#  include <sys/socket.h>
#  include <unistd.h>
#  include <fcntl.h>
#  include <cerrno>
#  include <ifaddrs.h>
#  include <net/if.h>
#  include <sys/ioctl.h> // SIOCGIFMTU (list_interfaces' include_all MTU lookup)
#  include <sys/stat.h> // stat() (list_interfaces' Wi-Fi-vs-Ethernet kind detection, Linux /sys/class/net probe)
#  define CLOSESOCK ::close
#  define LASTERR errno
#  define WOULDBLOCK EWOULDBLOCK
#endif

namespace netpulse {

// NOTE: Winsock init used to be a namespace-scope static object right here.
// That is unreliable in a static-lib build: a binary that links netpulse_core
// but never calls anything in *this* .obj (e.g. a test that only calls
// Session::resolve()) would never link this file in, so WSAStartup() would
// never run. Initialization now happens via ensure_winsock_ready() (see
// platform.hpp), called explicitly at the top of every function here that
// touches a socket API — see platform.hpp for the full explanation.

Prober::Prober(Family family, bool privileged, const std::string& source) : family_(family) {
    ensure_winsock_ready();
    int domain = (family == Family::V4) ? AF_INET : AF_INET6;
    int type = privileged ? SOCK_RAW : SOCK_DGRAM;
    int proto = (family == Family::V4) ? static_cast<int>(IPPROTO_ICMP)
                                       : static_cast<int>(IPPROTO_ICMPV6);
    long long s = static_cast<long long>(::socket(domain, type, proto));
    if (s < 0) {
        error_ = "socket() failed (need admin/root for raw ICMP)";
        fd_ = -1;
        return;
    }
    fd_ = s;

    // Optionally bind to a chosen local address so probes egress a specific NIC.
    std::string bind_addr = source;

#ifdef _WIN32
    // BUG FIX (Windows): a raw socket must be BOUND to a real local interface
    // address to receive. Left unbound, Windows delivers essentially nothing
    // to it — which is exactly what a live diagnostic capture showed: UDP mode
    // probing 30 hops for minutes produced ZERO inbound ICMP at the dispatcher
    // (no [netpulse-rx] lines at all), while the same code path works
    // unmodified on Linux, where an unbound raw socket still receives.
    //
    // Why ICMP mode still appeared to work while unbound: its replies are echo
    // replies to this host's own outbound echo requests, which the stack
    // associates with this process. A Time-Exceeded elicited by a UDP (or TCP)
    // packet is an ICMP ERROR generated by a third-party router about a
    // DIFFERENT socket's traffic, and nothing routes that to an unbound raw
    // socket. Binding is what makes the socket a legitimate destination for
    // ICMP addressed to this host, which is precisely what those errors are.
    //
    // When the user picked "Auto (default route)" there is no source address
    // to bind to, so discover the one the OS would actually use: open a UDP
    // socket, "connect" it (no packets are sent — connect() on UDP only sets
    // the peer and makes the kernel run its route lookup), then ask
    // getsockname() which local address that route selected. This is the
    // standard, dependency-free way to answer "which of my interfaces reaches
    // the internet", and it correctly follows the real routing table rather
    // than guessing the first non-loopback NIC.
    if (bind_addr.empty()) {
        int probe_domain = (family == Family::V4) ? AF_INET : AF_INET6;
        long long ps = static_cast<long long>(::socket(probe_domain, SOCK_DGRAM, IPPROTO_UDP));
        if (ps >= 0) {
            sockaddr_storage peer{};
            socklen_t peer_len = 0;
            if (family == Family::V4) {
                auto* p4 = reinterpret_cast<sockaddr_in*>(&peer);
                p4->sin_family = AF_INET;
                p4->sin_port = htons(53); // arbitrary; nothing is transmitted
                ::inet_pton(AF_INET, "8.8.8.8", &p4->sin_addr);
                peer_len = sizeof(*p4);
            } else {
                auto* p6 = reinterpret_cast<sockaddr_in6*>(&peer);
                p6->sin6_family = AF_INET6;
                p6->sin6_port = htons(53);
                ::inet_pton(AF_INET6, "2001:4860:4860::8888", &p6->sin6_addr);
                peer_len = sizeof(*p6);
            }
            if (::connect(static_cast<int>(ps), reinterpret_cast<sockaddr*>(&peer), peer_len) == 0) {
                sockaddr_storage loc{};
                socklen_t loc_len = sizeof(loc);
                if (::getsockname(static_cast<int>(ps), reinterpret_cast<sockaddr*>(&loc), &loc_len) == 0) {
                    char ip[INET6_ADDRSTRLEN]{};
                    if (loc.ss_family == AF_INET) {
                        if (::inet_ntop(AF_INET, &reinterpret_cast<sockaddr_in*>(&loc)->sin_addr, ip, sizeof(ip)))
                            bind_addr = ip;
                    } else {
                        if (::inet_ntop(AF_INET6, &reinterpret_cast<sockaddr_in6*>(&loc)->sin6_addr, ip, sizeof(ip)))
                            bind_addr = ip;
                    }
                }
            }
            CLOSESOCK(static_cast<int>(ps));
        }
    }
#endif

    if (!bind_addr.empty()) {
        int fd = static_cast<int>(fd_);
        bool bound = false;
        if (family == Family::V4) {
            sockaddr_in sa{};
            sa.sin_family = AF_INET;
            if (inet_pton(AF_INET, bind_addr.c_str(), &sa.sin_addr) == 1)
                bound = bind(fd, reinterpret_cast<sockaddr*>(&sa), sizeof(sa)) == 0;
        } else {
            sockaddr_in6 sa{};
            sa.sin6_family = AF_INET6;
            if (inet_pton(AF_INET6, bind_addr.c_str(), &sa.sin6_addr) == 1)
                bound = bind(fd, reinterpret_cast<sockaddr*>(&sa), sizeof(sa)) == 0;
        }
        // Deliberately NOT fatal, and deliberately not retried unbound: a
        // failed bind leaves the socket exactly as it was before (unbound),
        // i.e. the previous behaviour. So the worst case of this whole change
        // is "no better than before", never "worse" — which matters because
        // ICMP mode already works today and must not regress.
        debug_log(std::string("[netpulse-rx] raw ICMP socket bind to ") + bind_addr +
                  (bound ? " OK\n" : " FAILED (continuing unbound, as before)\n"));
#ifdef _WIN32
        // BUG FIX: binding alone is necessary but NOT sufficient on Windows.
        // Diagnostic evidence: with logging enabled and a UDP target actively
        // probing all 30 hops, the RX dispatcher logged ZERO packets — not
        // "arrived but uncorrelated", literally nothing arriving. So every
        // earlier attempt at this (all of which fixed correlation) was working
        // on the wrong layer: the OS was never handing these packets over.
        //
        // A bound raw ICMP socket on Windows still only receives ICMP the stack
        // considers "for" it. An ICMP Time-Exceeded / Port-Unreachable elicited
        // by a packet sent from a DIFFERENT socket — which is exactly what our
        // UDP and TCP probes are — does not qualify, so it is never surfaced.
        // SIO_RCVALL lifts precisely that restriction: the socket then sees the
        // ICMP present on the interface regardless of which socket owns the flow
        // that provoked it. That is the same capability other traceroute tools
        // pull in a capture driver (Npcap) to obtain.
        //
        // This also explains the long-standing asymmetry cleanly: ICMP mode
        // always worked on the very same machine at the very same moment,
        // because ITS replies are echo replies to this host's own probes, which
        // the stack does deliver normally.
        //
        // BUG FIX: this used to be gated `family == Family::V4` only, with a
        // claim that "SIO_RCVALL is not supported for IPv6 raw sockets" —
        // that claim was never actually verified against a real source, and
        // a live report of IPv6 TCP/UDP MTR and Ping simply not working
        // (matching the exact "raw socket receives nothing at all" symptom
        // that led to this fix in the first place, for IPv4) makes it worth
        // revisiting rather than trusting. The ioctl itself
        // (WSAIoctl(..., SIO_RCVALL, ...)) does not encode an address
        // family — it operates on whatever socket it's given — and this
        // call is already strictly best-effort with its own error handling
        // (checks the return code, logs either outcome, never treats
        // failure as fatal). Extending it to IPv6 costs nothing if it turns
        // out to be unsupported on some Windows version (the call simply
        // fails and logs that, exactly like an unelevated IPv4 attempt
        // already does today) and directly fixes the reported gap if it is
        // supported, which is the more likely case absent a confirmed
        // source for the original restriction.
        if (bound) {
            DWORD on = 1, returned = 0;
            int rc = ::WSAIoctl(static_cast<SOCKET>(fd_), SIO_RCVALL, &on, sizeof(on),
                                nullptr, 0, &returned, nullptr, nullptr);
            debug_log(rc == 0
                ? std::string("[netpulse-rx] SIO_RCVALL enabled — raw socket will now see ICMP errors elicited by UDP/TCP probes\n")
                : std::string("[netpulse-rx] SIO_RCVALL FAILED (err ") + std::to_string(LASTERR) +
                  ") — needs Administrator; TCP/UDP hop discovery will stay silent, ICMP mode unaffected\n");
        }
#endif
    }
    set_nonblocking();
}

Prober::~Prober() {
    if (fd_ >= 0) CLOSESOCK(static_cast<int>(fd_));
}

void Prober::set_nonblocking() {
#ifdef _WIN32
    u_long nb = 1;
    ioctlsocket(static_cast<int>(fd_), FIONBIO, &nb);
#else
    int fl = fcntl(static_cast<int>(fd_), F_GETFL, 0);
    fcntl(static_cast<int>(fd_), F_SETFL, fl | O_NONBLOCK);
#endif
}

bool Prober::send(const std::string& ip, uint8_t ttl, uint16_t id, uint16_t seq, size_t payload,
                  std::optional<uint16_t> pin_checksum) {
    if (fd_ < 0) return false;
    int fd = static_cast<int>(fd_);
    // Serializes {setsockopt TTL, sendto} — this socket may be shared by many
    // target threads at once (see the class comment in transport.hpp); TTL is
    // socket-level state, not a per-packet parameter, so two concurrent
    // sends with different TTLs could otherwise interleave and one probe
    // would silently go out with the WRONG TTL.
    std::lock_guard<std::mutex> lk(send_mtx_);

    if (family_ == Family::V4) {
        int t = ttl;
        setsockopt(fd, IPPROTO_IP, IP_TTL, reinterpret_cast<const char*>(&t), sizeof(t));
        sockaddr_in dst{};
        dst.sin_family = AF_INET;
        if (inet_pton(AF_INET, ip.c_str(), &dst.sin_addr) != 1) return false;
        auto pkt = build_echo(Family::V4, id, seq, payload, pin_checksum);
        return sendto(fd, reinterpret_cast<const char*>(pkt.data()), static_cast<int>(pkt.size()), 0,
                      reinterpret_cast<sockaddr*>(&dst), sizeof(dst)) >= 0;
    } else {
        int t = ttl;
        setsockopt(fd, IPPROTO_IPV6, IPV6_UNICAST_HOPS, reinterpret_cast<const char*>(&t), sizeof(t));
        sockaddr_in6 dst{};
        dst.sin6_family = AF_INET6;
        if (inet_pton(AF_INET6, ip.c_str(), &dst.sin6_addr) != 1) return false;
        auto pkt = build_echo(Family::V6, id, seq, payload);
        return sendto(fd, reinterpret_cast<const char*>(pkt.data()), static_cast<int>(pkt.size()), 0,
                      reinterpret_cast<sockaddr*>(&dst), sizeof(dst)) >= 0;
    }
}

std::vector<Incoming> Prober::drain_ready() {
    std::vector<Incoming> out;
    if (fd_ < 0) return out;
    int fd = static_cast<int>(fd_);
    uint8_t buf[1500];

    // Non-blocking: the shared RX dispatcher already knows (via its own
    // select() over every pooled socket) that this fd is readable RIGHT NOW —
    // this just drains whatever's queued and returns, no waiting here.
    for (;;) {
        sockaddr_storage src{};
        socklen_t slen = sizeof(src);
        long n = recvfrom(fd, reinterpret_cast<char*>(buf), sizeof(buf), 0,
                          reinterpret_cast<sockaddr*>(&src), &slen);
        if (n <= 0) break;
        double at = now_secs();
        std::optional<ParsedReply> r = (family_ == Family::V4)
                                           ? parse_v4(buf, static_cast<size_t>(n))
                                           : parse_v6(buf, static_cast<size_t>(n));
        if (r) {
            char ipstr[INET6_ADDRSTRLEN] = {0};
            if (src.ss_family == AF_INET) {
                auto* s4 = reinterpret_cast<sockaddr_in*>(&src);
                inet_ntop(AF_INET, &s4->sin_addr, ipstr, sizeof(ipstr));
            } else {
                auto* s6 = reinterpret_cast<sockaddr_in6*>(&src);
                inet_ntop(AF_INET6, &s6->sin6_addr, ipstr, sizeof(ipstr));
            }
            out.push_back(Incoming{std::string(ipstr), *r, at});
        }
    }
    return out;
}

// ---------------------------------------------------------------------------
// Socket pool (see the doc comment on acquire_pooled_socket in transport.hpp).
namespace {
struct SocketPoolKey {
    Family family;
    bool privileged;
    std::string source;
    bool operator<(const SocketPoolKey& o) const {
        if (family != o.family) return family < o.family;
        if (privileged != o.privileged) return privileged < o.privileged;
        return source < o.source;
    }
};
struct SocketPool {
    std::mutex mtx;
    std::map<SocketPoolKey, std::weak_ptr<Prober>> table;
};
inline SocketPool& g_socket_pool() { static SocketPool* p = new SocketPool(); return *p; } // leaked singleton (process lifetime, never destroyed — same pattern as the other g_* singletons in session.cpp)
} // namespace

std::shared_ptr<Prober> acquire_pooled_socket(Family family, bool privileged, const std::string& source) {
    SocketPoolKey key{family, privileged, source};
    SocketPool& pool = g_socket_pool();
    std::lock_guard<std::mutex> lk(pool.mtx);
    std::weak_ptr<Prober>& slot = pool.table[key]; // default-constructs an already-expired weak_ptr if new
    if (auto existing = slot.lock()) return existing;
    auto sock = std::make_shared<Prober>(family, privileged, source);
    slot = sock; // overwrite whatever was there (nothing, or an expired weak_ptr) — always safe under this same lock
    return sock;
}

std::vector<std::shared_ptr<Prober>> list_active_pooled_sockets() {
    std::vector<std::shared_ptr<Prober>> out;
    SocketPool& pool = g_socket_pool();
    std::lock_guard<std::mutex> lk(pool.mtx);
    out.reserve(pool.table.size());
    for (auto& [key, weak] : pool.table) {
        if (auto s = weak.lock()) out.push_back(std::move(s));
    }
    return out;
}

namespace {
// Best-effort virtual/hypervisor/VPN adapter name heuristic — shared by both
// platform branches below. These are never Wi-Fi or "real" Ethernet, and
// calling them "Ethernet" (the generic fallback) would be actively
// misleading in the diagnostics list, so they get their own bucket.
bool looks_virtual(const std::string& name) {
    static const char* prefixes[] = {
        "veth", "docker", "br-", "virbr", "tun", "tap", "vmnet", "vmware",
        "vethernet", "vEthernet", "VMware", "Hyper-V", "WSL", "utun",
        "bridge", "zt", "tailscale", "wg",
    };
    std::string lower = name;
    for (auto& c : lower) c = static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
    for (auto* p : prefixes) {
        std::string pl = p;
        for (auto& c : pl) c = static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
        if (lower.rfind(pl, 0) == 0) return true;
    }
    return false;
}
} // namespace

#ifdef _WIN32
// Windows: IF_TYPE_IEEE80211 (71) is the standard IANA ifType for Wi-Fi
// adapters (ipifcons.h — checked by value like IF_TYPE_SOFTWARE_LOOPBACK
// above, for the same MinGW/MSVC-SDK-header-variance reason).
// IF_TYPE_ETHERNET_CSMACD (6) covers real wired NICs.
static std::string classify_kind(ULONG if_type, const std::string& name) {
    if (looks_virtual(name)) return "Virtual";
    if (if_type == 71) return "Wi-Fi";
    if (if_type == 6) return "Ethernet";
    return "Other";
}
#else
// POSIX: a genuinely wireless net device exposes a "wireless" (legacy WEXT)
// or "phy80211" (modern nl80211/cfg80211) entry under
// /sys/class/net/<name>/ on Linux — checking for either covers old and new
// kernels without needing a wireless-extensions header this project doesn't
// otherwise depend on. This is Linux-specific (no /sys on macOS/BSD); on
// those platforms it falls through to the name heuristic below, which is
// necessarily weaker (macOS's "en0" convention doesn't distinguish Wi-Fi
// from Ethernet in the name at all) — best-effort, not exhaustive.
static std::string classify_kind(const std::string& name) {
    if (looks_virtual(name)) return "Virtual";
#ifdef __linux__
    struct stat st{};
    if (::stat(("/sys/class/net/" + name + "/wireless").c_str(), &st) == 0) return "Wi-Fi";
    if (::stat(("/sys/class/net/" + name + "/phy80211").c_str(), &st) == 0) return "Wi-Fi";
#endif
    // Common cross-distro/BSD wireless naming conventions as a fallback.
    if (name.rfind("wl", 0) == 0 || name.rfind("wifi", 0) == 0) return "Wi-Fi";
    if (name.rfind("en", 0) == 0 || name.rfind("eth", 0) == 0) return "Ethernet";
    return "Other";
}
#endif

std::vector<NetInterface> list_interfaces(bool include_all) {
    ensure_winsock_ready();
    std::vector<NetInterface> out;
#ifdef _WIN32
    ULONG flags = GAA_FLAG_SKIP_ANYCAST | GAA_FLAG_SKIP_MULTICAST | GAA_FLAG_SKIP_DNS_SERVER;
    ULONG size = 15000;
    std::vector<uint8_t> buf(size);
    auto* addrs = reinterpret_cast<IP_ADAPTER_ADDRESSES*>(buf.data());
    if (GetAdaptersAddresses(AF_UNSPEC, flags, nullptr, addrs, &size) == ERROR_BUFFER_OVERFLOW) {
        buf.resize(size);
        addrs = reinterpret_cast<IP_ADAPTER_ADDRESSES*>(buf.data());
    }
    if (GetAdaptersAddresses(AF_UNSPEC, flags, nullptr, addrs, &size) == NO_ERROR) {
        for (auto* a = addrs; a; a = a->Next) {
            bool up = (a->OperStatus == IfOperStatusUp);
            if (!up && !include_all) continue;
            // IF_TYPE_SOFTWARE_LOOPBACK == 24 (standard IANA ifType value,
            // ipifcons.h) — checked by value rather than requiring that
            // header directly, since which header actually defines it
            // varies across MinGW/MSVC SDK versions and iphlpapi.h already
            // transitively provides everything else this function needs.
            bool loopback = (a->IfType == 24);
            if (loopback && !include_all) continue;
            char name[256] = {0};
            WideCharToMultiByte(CP_UTF8, 0, a->FriendlyName, -1, name, sizeof(name), nullptr, nullptr);
            uint32_t mtu = (a->Mtu != 0xFFFFFFFF) ? static_cast<uint32_t>(a->Mtu) : 0; // 0xFFFFFFFF = "unknown" per MSDN
            std::string kind = loopback ? "Other" : classify_kind(a->IfType, name);
            for (auto* u = a->FirstUnicastAddress; u; u = u->Next) {
                char ip[INET6_ADDRSTRLEN] = {0};
                auto* sa = u->Address.lpSockaddr;
                if (sa->sa_family == AF_INET) {
                    inet_ntop(AF_INET, &reinterpret_cast<sockaddr_in*>(sa)->sin_addr, ip, sizeof(ip));
                    out.push_back({name, ip, false, up, loopback, mtu, kind});
                } else if (sa->sa_family == AF_INET6) {
                    inet_ntop(AF_INET6, &reinterpret_cast<sockaddr_in6*>(sa)->sin6_addr, ip, sizeof(ip));
                    out.push_back({name, ip, true, up, loopback, mtu, kind});
                }
            }
        }
    }
#else
    struct ifaddrs* ifap = nullptr;
    if (getifaddrs(&ifap) == 0) {
        for (auto* ifa = ifap; ifa; ifa = ifa->ifa_next) {
            if (!ifa->ifa_addr) continue;
            bool up = !!(ifa->ifa_flags & IFF_UP);
            bool loopback = !!(ifa->ifa_flags & IFF_LOOPBACK);
            if (!include_all && (!up || loopback)) continue;
            uint32_t mtu = 0;
            if (include_all && ifa->ifa_name) {
                // ifaddrs doesn't carry MTU itself — SIOCGIFMTU is the
                // portable (Linux/BSD/macOS) way to ask for it. Best-effort:
                // a failure (e.g. sandboxed/restricted environment) just
                // leaves mtu at its "unknown" default of 0, same as an
                // OS/adapter that genuinely doesn't report one.
                int mtu_fd = ::socket(AF_INET, SOCK_DGRAM, 0);
                if (mtu_fd >= 0) {
                    struct ifreq ifr{};
                    std::strncpy(ifr.ifr_name, ifa->ifa_name, IFNAMSIZ - 1);
                    if (::ioctl(mtu_fd, SIOCGIFMTU, &ifr) == 0) mtu = static_cast<uint32_t>(ifr.ifr_mtu);
                    ::close(mtu_fd);
                }
            }
            char ip[INET6_ADDRSTRLEN] = {0};
            std::string ifname = ifa->ifa_name ? ifa->ifa_name : "";
            std::string kind = loopback ? "Other" : classify_kind(ifname);
            if (ifa->ifa_addr->sa_family == AF_INET) {
                inet_ntop(AF_INET, &reinterpret_cast<sockaddr_in*>(ifa->ifa_addr)->sin_addr, ip, sizeof(ip));
                out.push_back({ifname, ip, false, up, loopback, mtu, kind});
            } else if (ifa->ifa_addr->sa_family == AF_INET6) {
                inet_ntop(AF_INET6, &reinterpret_cast<sockaddr_in6*>(ifa->ifa_addr)->sin6_addr, ip, sizeof(ip));
                out.push_back({ifname, ip, true, up, loopback, mtu, kind});
            }
        }
        freeifaddrs(ifap);
    }
#endif
    return out;
}

// ---------------------------------------------------------------------------
// Local egress address for a destination — the "UDP connect() trick".
//
// Exists to let the shared-hop cache (SharedHopTable, session.cpp) safely
// extend cross-target caching to PRIVATE/CGNAT hop IPs, not just public ones.
// The original public-only restriction is because a private IP (192.168.x,
// 10.x, ...) is only unambiguous WITHIN one routing domain — the same
// address can be two different physical devices reached via two different
// local interfaces (e.g. the physical NIC vs. a VPN's virtual adapter). The
// cache is already keyed in part by the session's configured `source_addr`,
// but that's usually left empty (most targets don't explicitly bind an
// egress interface), which collapses every such session onto the same empty
// key component regardless of which interface the OS actually routes them
// through — exactly the ambiguity the public-only restriction exists to
// avoid.
//
// A raw ICMP socket that isn't bound or connected doesn't help here:
// getsockname() on it just returns the unspecified address (0.0.0.0/::)
// until the kernel has actually committed to a route, which sendto() does
// per-packet rather than once up front. Instead, this opens a throwaway
// UDP socket, connect()s it to the real destination (this never sends a
// packet — UDP connect() only consults the routing table and records which
// local address it would use), reads that decision back via getsockname(),
// and closes the socket immediately. That's the OS's own routing table
// answering "which interface would traffic to THIS destination actually
// leave from" — the same decision it makes for the real probes — so two
// sessions whose destinations route out different interfaces get
// correspondingly different keys automatically, with no configuration
// required, while two sessions that genuinely share an egress (the common
// case) correctly collapse onto the same one and share the cache benefit.
//
// std::nullopt on any failure (no route, sandboxed/offline environment,
// etc.) — callers must treat that as "could not establish a safe cache key"
// and fall back to the existing public-only behavior for that session
// rather than guessing.
std::optional<std::string> local_egress_ip(Family family, const std::string& dest_ip) {
    if (dest_ip.empty()) return std::nullopt;
    ensure_winsock_ready();
    int af = (family == Family::V4) ? AF_INET : AF_INET6;
#ifdef _WIN32
    SOCKET fd = socket(af, SOCK_DGRAM, IPPROTO_UDP);
    if (fd == INVALID_SOCKET) return std::nullopt;
#else
    int fd = socket(af, SOCK_DGRAM, IPPROTO_UDP);
    if (fd < 0) return std::nullopt;
#endif
    bool ok = false;
    std::string result;
    if (family == Family::V4) {
        sockaddr_in dst{};
        dst.sin_family = AF_INET;
        dst.sin_port = htons(53); // arbitrary — never actually sent to
        if (inet_pton(AF_INET, dest_ip.c_str(), &dst.sin_addr) == 1 &&
            connect(fd, reinterpret_cast<sockaddr*>(&dst), sizeof(dst)) == 0) {
            sockaddr_in local{};
            socklen_t len = sizeof(local);
            if (getsockname(fd, reinterpret_cast<sockaddr*>(&local), &len) == 0) {
                char ip[INET6_ADDRSTRLEN] = {0};
                if (inet_ntop(AF_INET, &local.sin_addr, ip, sizeof(ip))) { result = ip; ok = true; }
            }
        }
    } else {
        sockaddr_in6 dst{};
        dst.sin6_family = AF_INET6;
        dst.sin6_port = htons(53);
        if (inet_pton(AF_INET6, dest_ip.c_str(), &dst.sin6_addr) == 1 &&
            connect(fd, reinterpret_cast<sockaddr*>(&dst), sizeof(dst)) == 0) {
            sockaddr_in6 local{};
            socklen_t len = sizeof(local);
            if (getsockname(fd, reinterpret_cast<sockaddr*>(&local), &len) == 0) {
                char ip[INET6_ADDRSTRLEN] = {0};
                if (inet_ntop(AF_INET6, &local.sin6_addr, ip, sizeof(ip))) { result = ip; ok = true; }
            }
        }
    }
    CLOSESOCK(fd);
    if (!ok || result.empty() || result == "0.0.0.0" || result == "::") return std::nullopt;
    return result;
}

} // namespace netpulse
